FROM python:3.6
RUN cp /etc/apt/sources.list /etc/apt/sources.list.bak
COPY docker/sources.list /etc/apt/sources.list
RUN apt-get update
RUN apt-get install vim -y
RUN apt-get install libgl1 -y

RUN pip install matplotlib -i https://pypi.doubanio.com/simple/

RUN pip install chardet -i https://pypi.doubanio.com/simple/
RUN pip install paddlehub==2.1.0 -i https://pypi.doubanio.com/simple/
RUN pip install paddlepaddle==2.3.0 -i https://pypi.doubanio.com/simple/
RUN pip install paddlex==1.3.10 -i https://pypi.doubanio.com/simple/
